services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telegram_bot
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - PHONE=${PHONE}
      - CHAT_USERNAME=${CHAT_USERNAME}
      - SELF_USERNAME=${SELF_USERNAME}
    volumes:
      - .:/app
    depends_on:
      - flask

  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask_server
    ports:
      - "3030:3030"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development