FROM python:3.11-slim

# Set environment variables to prevent Python from writing .pyc files to disk and buffering stdout and stderr
ENV PYTHONUNBUFFERED 1

WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY . /app

CMD ["python", "server.py"]
